---
docker_compose_path: "{{ docker.compose_path }}"
deploy_use_color: false
service_name_short: "{{service_name|replace('_', '-')}}"
consul_port: 8500
consul_token: "{% if consul is mapping and 'master_token' in consul %}{{ consul.master_token }}{% endif %}"
